add licenses screen

diff --git a/.github/workflows/test-and-build.yaml b/.github/workflows/test-and-build.yaml
--- a/.github/workflows/test-and-build.yaml
+++ b/.github/workflows/test-and-build.yaml
@@ -42,6 +42,14 @@ jobs:
                   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                   SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
 
+            - name: Check missing licenses
+              run: |
+                  missing=$(node ./scripts/extract-licenses.cjs | jq .ko)
+                  if [ "$missing" != "[]" ]; then
+                    echo "Error: Missing licenses found: $missing"
+                    exit 1
+                  fi
+
             - uses: actions/upload-artifact@v4
               with:
                   name: node_modules
